/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColeccionRouteImport } from './routes/coleccion'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as RgAdminRouteImport } from './routes/rg-admin'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionRoute = ColeccionRouteImport.update({
  id: '/coleccion',
  path: '/coleccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const RgAdminRoute = RgAdminRouteImport.update({
  id: '/rg-admin',
  path: '/rg-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/contacto': typeof ContactoRoute
  '/rg-admin': typeof RgAdminRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/contacto': typeof ContactoRoute
  '/rg-admin': typeof RgAdminRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/contacto': typeof ContactoRoute
  '/rg-admin': typeof RgAdminRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/coleccion' | '/contacto' | '/rg-admin' | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coleccion' | '/contacto' | '/rg-admin' | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/coleccion'
    | '/contacto'
    | '/rg-admin'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColeccionRoute: typeof ColeccionRoute
  ContactoRoute: typeof ContactoRoute
  RgAdminRoute: typeof RgAdminRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion': {
      id: '/coleccion'
      path: '/coleccion'
      fullPath: '/coleccion'
      preLoaderRoute: typeof ColeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rg-admin': {
      id: '/rg-admin'
      path: '/rg-admin'
      fullPath: '/rg-admin'
      preLoaderRoute: typeof RgAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColeccionRoute: ColeccionRoute,
  ContactoRoute: ContactoRoute,
  RgAdminRoute: RgAdminRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
